# Generated by Django 4.2.7 on 2023-11-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_description_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Nom', max_length=255),
        ),
    ]
