# Generated by Django 4.2.7 on 2023-11-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_published_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published',
        ),
    ]
