app = "studimercadonajf"

[build]
  image = "python:3.12.0"

[services]
  [[services.ports]]
    handlers = ["http"]
    internal_port = 8000

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[experimental]
  allowed_public_ports = [80, 443]

[[services.tcp_checks]]
  interval = 10000
  timeout = 2000
